name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files via RSYNC
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='node_modules' --exclude='*.log' ./ deploy@${{ secrets.EC2_HOST }}:/home/deploy/app/
      - name: Execute remote SSH commands
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/deploy/app
            yarn install --production
            yarn build
            pm2 restart nextjs-app || pm2 start yarn --name "nextjs-app" -- start
          EOF
