name: CI/CD for CapRover

on:
  push:
    branches:
      - production  # Ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t teste-caprover .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push teste-caprover

      - name: Deploy to CapRover
        env:
          CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
          CAPROVER_APP_NAME: ${{ secrets.CAPROVER_APP_NAME }}
          CAPROVER_TOKEN: ${{ secrets.CAPROVER_TOKEN }}
        run: |
          curl -X POST "${CAPROVER_SERVER}/api/v2/apps/${CAPROVER_APP_NAME}/deploy" \
          -H "Authorization: Bearer ${CAPROVER_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{"image": "teste-caprover"}'
